name: Nikiton Cloud Build — KazFishing Mobile

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build-android:
    runs-on: ubuntu-latest
    env:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      UNITY_VERSION: 6000.0.60f1
      PROJECT_PATH: game
      BUILD_NAME: kazfishing
      VERSION_FILE: build/version.json
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Read version.json
        id: ver
        run: |
          VERSION=$(jq -r '.version' ${{ env.VERSION_FILE }})
          CODE=$(jq -r '.build_code' ${{ env.VERSION_FILE }})
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "code=$CODE" >> $GITHUB_OUTPUT

      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: ${{ env.PROJECT_PATH }}/Library
          key: Library-${{ env.UNITY_VERSION }}-${{ hashFiles('**/Packages/manifest.json') }}
          restore-keys: |
            Library-${{ env.UNITY_VERSION }}-

      - name: Build APK
        uses: game-ci/unity-builder@v4
        with:
          unityVersion: ${{ env.UNITY_VERSION }}
          targetPlatform: Android
          projectPath: ${{ env.PROJECT_PATH }}
          buildName: ${{ env.BUILD_NAME }}_${{ steps.ver.outputs.version }}
          versioning: Custom
          version: ${{ steps.ver.outputs.version }}
          androidVersionCode: ${{ steps.ver.outputs.code }}
          androidExportType: androidPackage

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: kazfishing_${{ steps.ver.outputs.version }}.apk
          path: build/Android/${{ env.BUILD_NAME }}_${{ steps.ver.outputs.version }}.apk

      - name: Build AAB
        uses: game-ci/unity-builder@v4
        with:
          unityVersion: ${{ env.UNITY_VERSION }}
          targetPlatform: Android
          projectPath: ${{ env.PROJECT_PATH }}
          buildName: ${{ env.BUILD_NAME }}_${{ steps.ver.outputs.version }}
          versioning: Custom
          version: ${{ steps.ver.outputs.version }}
          androidVersionCode: ${{ steps.ver.outputs.code }}
          androidExportType: androidAppBundle

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: kazfishing_${{ steps.ver.outputs.version }}.aab
          path: build/Android/${{ env.BUILD_NAME }}_${{ steps.ver.outputs.version }}.aab

      - name: Pack project ZIP (core+game+legal+branding)
        run: |
          mkdir -p build/output
          zip -r build/output/nikiton_kazfishing_${{ steps.ver.outputs.version }}.zip core game legal branding build/version.json || true

      - name: Upload ZIP
        uses: actions/upload-artifact@v4
        with:
          name: nikiton_kazfishing_${{ steps.ver.outputs.version }}.zip
          path: build/output/nikiton_kazfishing_${{ steps.ver.outputs.version }}.zip

