name: Nikiton Cloud Build — KazFishing Mobile

on:
  workflow_dispatch:

jobs:
  build-android:
    name: Build Android (APK + AAB + ZIP)
    runs-on: ubuntu-latest

    env:
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      UNITY_VERSION: 6000.0.60f1
      PROJECT_PATH: games/KazFishingMobile
      BUILD_TARGET: Android
      BUILD_NAME: kazfishing_1.0.0
      BUILD_PATH: build/Android
      BUILD_FILE: kazfishing_1.0.0.apk
      VERSION: 1.0.0
      ANDROID_VERSION_CODE: 1
      BUILD_ZIP_NAME: nikiton_kazfishing_1.0.0.zip

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ env.UNITY_VERSION }}
          restore-keys: |
            Library-

      - name: Build APK
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android
          unityVersion: ${{ env.UNITY_VERSION }}
          projectPath: ${{ env.PROJECT_PATH }}
          buildName: ${{ env.BUILD_NAME }}
          buildPath: ${{ env.BUILD_PATH }}
          buildFile: ${{ env.BUILD_FILE }}
          allowDirtyBuild: true

      - name: Upload APK
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: KazFishing-APK
          path: ${{ env.BUILD_PATH }}/${{ env.BUILD_FILE }}

      - name: Build AAB
        if: always()
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android
          unityVersion: ${{ env.UNITY_VERSION }}
          projectPath: ${{ env.PROJECT_PATH }}
          buildName: ${{ env.BUILD_NAME }}
          buildPath: ${{ env.BUILD_PATH }}
          buildFile: kazfishing_1.0.0.aab
          androidExportType: androidAppBundle
          allowDirtyBuild: true

      - name: Upload AAB
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: KazFishing-AAB
          path: ${{ env.BUILD_PATH }}/kazfishing_1.0.0.aab

      - name: Pack project ZIP (core+game+legal+branding)
        if: always()
        run: |
          zip -r ${{ env.BUILD_ZIP_NAME }} core games legal branding

      - name: Upload ZIP
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: NikitonCloud-FullPackage
          path: ${{ env.BUILD_ZIP_NAME }}

      - name: Complete job
        if: always()
        run: echo "✅ Build process completed successfully."
