name: Android Build

on:
  workflow_dispatch:

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest

    env:
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      UNITY_ACTIVATION_METHOD: PERSONAL
      UNITY_VERSION: 6000.0.60f1
      PROJECT_PATH: game

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Unity Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('**/Packages/manifest.json') }}
          restore-keys: |
            Library-

      - name: Build Android APK
        uses: game-ci/unity-builder@v4
        with:
          targetPlatform: Android
          unityVersion: 6000.0.60f1
          projectPath: ${{ env.PROJECT_PATH }}
          buildName: kazfishing_1.0.0
          buildFile: build/Android/kazfishing_1.0.0.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: KazFishing APK
          path: build/Android/kazfishing_1.0.0.apk

      - name: Build Android AAB
        uses: game-ci/unity-builder@v4
        with:
          targetPlatform: Android
          unityVersion: 6000.0.60f1
          androidExportType: androidAppBundle
          projectPath: ${{ env.PROJECT_PATH }}
          buildName: kazfishing_1.0.0
          buildFile: build/Android/kazfishing_1.0.0.aab

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: KazFishing AAB
          path: build/Android/kazfishing_1.0.0.aab
