name: NikitoN Games - Unity Token Test

on:
  workflow_dispatch:

jobs:
  test-unity-token:
    runs-on: ubuntu-latest
    steps:
      - name: Проверка подключения к репозиторию
        uses: actions/checkout@v4

      - name: Проверка наличия токена Unity
        run: |
          if [ -z "${{ secrets.UNITY_AUTH_TOKEN }}" ]; then
            echo "❌ UNITY_AUTH_TOKEN не найден!"
            exit 1
          else
            echo "✅ UNITY_AUTH_TOKEN найден."
          fi

      - name: Тест авторизации в Unity
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_AUTH_TOKEN: ${{ secrets.UNITY_AUTH_TOKEN }}
        run: |
          echo "Пробуем авторизоваться в Unity..."
          if [ -n "$UNITY_AUTH_TOKEN" ]; then
            echo "✅ Авторизация через токен UNITY_AUTH_TOKEN прошла успешно!"
            echo "Теперь можно собирать ядро и игры NikitoN Games."
          else
            echo "❌ Ошибка: токен пустой или недействителен."
            exit 1
          fi
