name: Nikiton Cloud Build — KazFishing Mobile

on:
  workflow_dispatch:

env:
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_ACTIVATION_METHOD: PERSONAL
  UNITY_VERSION: 6000.0.60f1
  PROJECT_PATH: game
  BUILD_NAME: kazfishing_1.0.0
  BUILD_PATH: build/Android

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cache Unity Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ env.UNITY_VERSION }}
          restore-keys: |
            Library-

      - name: Activate Unity License
        uses: game-ci/unity-activate@v3
        with:
          unityVersion: ${{ env.UNITY_VERSION }}
          activationMethod: ${{ env.UNITY_ACTIVATION_METHOD }}
          personalLicense: ${{ env.UNITY_LICENSE }}
          email: ${{ env.UNITY_EMAIL }}
          password: ${{ env.UNITY_PASSWORD }}

      - name: Build APK
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: Android
          projectPath: ${{ env.PROJECT_PATH }}
          buildName: ${{ env.BUILD_NAME }}
          versioning: Custom
          version: 1.0.0
          androidExportType: androidPackage

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: KazFishing-APK
          path: ${{ env.BUILD_PATH }}/${{ env.BUILD_NAME }}.apk

      - name: Build AAB
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: Android
          androidExportType: androidAppBundle
          projectPath: ${{ env.PROJECT_PATH }}
          buildName: ${{ env.BUILD_NAME }}
          versioning: Custom
          version: 1.0.0

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: KazFishing-AAB
          path: ${{ env.BUILD_PATH }}/${{ env.BUILD_NAME }}.aab

      - name: Pack project ZIP (core+game+legal+branding)
        run: |
          zip -r ${{ env.BUILD_NAME }}.zip core game legal branding
        shell: bash

      - name: Upload ZIP
        uses: actions/upload-artifact@v4
        with:
          name: KazFishing-ZIP
          path: ./${{ env.BUILD_NAME }}.zip
