name: Nikiton Cloud Build — KazFishing Mobile

on:
  workflow_dispatch:

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest

    env:
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      UNITY_ACTIVATION_METHOD: PERSONAL
      UNITY_VERSION: 6000.0.60f1
      PROJECT_PATH: game/KazFishingMobile
      BUILD_NAME: kazfishing_1.0.0
      BUILD_FILE: kazfishing_1.0.0.apk
      BUILD_PATH: build/Android

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cache Unity Library
        uses: actions/cache@v3
        with:
          path: ${{ env.PROJECT_PATH }}/Library
          key: Library-${{ env.UNITY_VERSION }}
          restore-keys: |
            Library-

      - name: Unity Build (Android)
        uses: game-ci/unity-builder@v4
        with:
          targetPlatform: Android
          unityVersion: ${{ env.UNITY_VERSION }}
          projectPath: ${{ env.PROJECT_PATH }}
          buildName: ${{ env.BUILD_NAME }}
          buildFile: ${{ env.BUILD_FILE }}
          buildPath: ${{ env.BUILD_PATH }}
          allowDirtyBuild: true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILD_FILE }}
          path: ${{ env.PROJECT_PATH }}/${{ env.BUILD_PATH }}/${{ env.BUILD_FILE }}
