name: Generate Catalog
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate catalog.json
        run: |
          cd games/KazFishingMobile/content
          mkdir -p packs
          echo "{
            \"version\": \"$(date +%Y.%m.%d-%H.%M)\",
            \"items\": [" > catalog.json

          first=1
          for f in packs/*.zip; do
            [ -f \"$f\" ] || continue
            base=$(basename \"$f\" .zip)
            title=$(echo \"$base\" | sed -E 's/_/ /g')
            size_mb=$(python3 -c "import os; print(round(os.path.getsize('$f')/1024/1024,1))")
            url=\"https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/main/games/KazFishingMobile/content/packs/$base.zip\"

            if [ $first -eq 0 ]; then
              echo \",\" >> catalog.json
            fi
            first=0

            echo \"  {\\\"id\\\":\\\"$base\\\",\\\"type\\\":\\\"pack\\\",\\\"title\\\":\\\"$title\\\",\\\"size_mb\\\":$size_mb,\\\"url\\\":\\\"$url\\\"}\" >> catalog.json
          done

          echo \"]}\" >> catalog.json

      - name: Commit and push
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "GitHub Actions"
          git add games/KazFishingMobile/content/catalog.json
          git commit -m "Update catalog.json automatically"
          git push
